### ISSUE TITLE
SSH incorrect password in the documentary

### ISSUE THREAD

**Issue by Robnex** [Yumi-Lab/YumiOS#12]
### What happened

Hello,

i want to login via ssh to the smartpad.

Use credentials out of your docu
[https://wiki.yumi-lab.com/KlipperSmartPad/Tuto/Remote_multi_printers/]

name: pi
PW: fun

-> that was inccorect

In your github i found the following credentials

name: pi
pw: yumi

-> That worked

### What did you expect to happen

Login into the system

### How to reproduce

Try a few times

**Comment by xtrack33** [comment]
thank we will fix it

**Comment by PAPAMICA** [comment]
Hello,

Je n'arrive toujours pas à me connecter en SSH : 
```
mickael@MacBook-Pro-de-Mickael > ssh pi@10.10.0.220
pi@10.10.0.220: Permission denied (publickey,password).
```

C'est toujours bien l'utilisateur `pi`qu'il faut utiliser ? (`root` ne fonctionne pas non plus si jamais)
