### ISSUE TITLE
No Image of the YumiOS available on github and your documentation

### ISSUE THREAD

**Issue by Robnex** [Yumi-Lab/YumiOS#13]
### What happened

Hello,

I want to setup a second SD card as Backup.
But there is no upload or link to your Yumi OS for the smart pad.

Would it be possible to upload one?

### What did you expect to happen

Download the YumiOS out of Github or a Cloud

### How to reproduce

Search again the Docu and Github

**Comment by xtrack33** [comment]
i will check this point to improve

**Comment by xtrack33** [comment]
https://github.com/Yumi-Lab/YumiOS/releases
